import { unstable_noStore as noStore } from "next/cache";
import Link from "next/link";

import { CreatePost } from "~/app/_components/create-post";
import { getServerAuthSession } from "~/server/auth";
import { api } from "~/trpc/server";
import Head from "next/head";

export default async function Home() {
  noStore();
  // const hello = await api.post.hello.query({ text: "from tRPC" });
  const session = await getServerAuthSession();

  return (
    <>
      <Head>
        <title>T3 App - Posts</title>
        <link rel="icon" href="/favicon.ico" /> 
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <Link
          href={session ? "/api/auth/signout" : "/api/auth/signin"}
          className="rounded-full bg-white/10 px-10 py-3 font-semibold no-underline transition hover:bg-white/20"
        >
          {session ? "Sign out" : "Sign in"}
        </Link>
          
        <ShowAll />      

        <CreatePost />

        {/* <CrudShowcase /> */}
      </main>
    </>
  );

  async function ShowAll() {
    const session = await getServerAuthSession();
    if (!session?.user) return null;

    const posts = await api.post.getAll.query();

    return (
      <div className="w-full max-w-xs">
        {posts.length ? (
          <ul>
            {posts.map((post) => (
              <li key={post.id}>{post.name}</li>
            ))}
          </ul>
        ) : (
          <p>You have no posts yet.</p>
        )}
      </div>
    );
  };

// async function CrudShowcase() {
//   const session = await getServerAuthSession();
//   if (!session?.user) return null;

//   const latestPost = await api.post.getLatest.query();

//   return (
//     <div className="w-full max-w-xs">
//       {latestPost ? (
//         <p className="truncate">Your most recent post: {latestPost.name}</p>
//       ) : (
//         <p>You have no posts yet.</p>
//       )}

//       <CreatePost />
//     </div>
//   );
}
